# Generated by Django 4.2 on 2024-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=100)),
                ('date', models.DateTimeField(max_length=100)),
                ('time', models.TimeField(max_length=100)),
                ('number_guests', models.CharField(max_length=100)),
            ],
        ),
    ]
