# Generated by Django 4.2 on 2024-01-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
