# Generated by Django 4.2 on 2024-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
