# Generated by Django 4.2 on 2024-01-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_table_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Book_Table',
        ),
    ]
