# Generated by Django 4.2 on 2024-01-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_table_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_table',
            options={'verbose_name_plural': 'Table_Bookings'},
        ),
    ]
